title: 카페인 중독자
description: "Satellite - jekyll blog theme"
logo_img: "/assets/img/favicon.webp"
profile_img: "/assets/img/profile2.jpg"

# Social Links
email: abc8325767@gmail.com
github_username: SeongWooJo
twitter_username: twitter
instagram_username: instagram
linkedin_username: linkedin
facebook_username: facebook

# External API
giscus_repo: "SeongWooJo/SeongWooJo.github.io"
giscus_repoId: "R_kgDOPIMrXA"
giscus_category: "Q&A"
giscus_categoryId: "DIC_kwDOPIMrXM4Cx7Sw"
goatcounter_code: seongwoojo
google_analytics:
google_site_verification: nb_BBOCn4QR_6xUVHV_-97hZaCiSdhQZzPUkrpm6gts
naver_site_verification: 1e6c99b3cb8dcbbbbdb4f07f256134cc5ba87ea2

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /myblog
baseurl:

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-loading-lazy

exclude:
  - docs/

collections:
  pages:
    output: true
    permalink: /:path.html

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      date: "2025-08-01 12:00:00"

# Markdown newline activator 
kramdown:
  input: GFM
  hard_wrap: true